using System;
using System.Collections.Generic;

namespace Inspire.Erp.Domain.Entities
{
    public partial class ReportPurchaseVoucher
    {

        //////public int PurchaseVoucherPurId { get; set; }
        //////public string PurchaseVoucherVoucherNo { get; set; }
        //////public DateTime PurchaseVoucherPurchaseDate { get; set; }
        //////public string PurchaseVoucherPurchaseType { get; set; }
        //////public int? PurchaseVoucherPartyId { get; set; }
        //////public string PurchaseVoucherPartyName { get; set; }
        //////public string PurchaseVoucherPartyAddress { get; set; }
        //////public string PurchaseVoucherPartyVatNo { get; set; }
        //////public string PurchaseVoucherPurchaseRef { get; set; }
        //////public string PurchaseVoucherSupplyInvoiceNo { get; set; }
        //////public string PurchaseVoucherGrno { get; set; }
        //////public DateTime? PurchaseVoucherGrdate { get; set; }
        //////public string PurchaseVoucherLpono { get; set; }
        //////public DateTime? PurchaseVoucherLpodate { get; set; }
        //////public string PurchaseVoucherQuatationNo { get; set; }
        //////public DateTime? PurchaseVoucherQuatationDate { get; set; }
        //////public string PurchaseVoucherDescription { get; set; }
        //////public bool? PurchaseVoucherExcludeVat { get; set; }
        //////public string PurchaseVoucherPono { get; set; }
        //////public string PurchaseVoucherBatchCode { get; set; }
        //////public string PurchaseVoucherDayBookNo { get; set; }
        //////public int? PurchaseVoucherLocationId { get; set; }
        //////public int? PurchaseVoucherUserId { get; set; }
        //////public int? PurchaseVoucherCurrencyId { get; set; }
        //////public int? PurchaseVoucherCompanyId { get; set; }
        //////public int? PurchaseVoucherJobId { get; set; }
        //////public int? PurchaseVoucherFsno { get; set; }
        //////public decimal? PurchaseVoucherFcRate { get; set; }
        //////public string PurchaseVoucherStatus { get; set; }
        //////public decimal? PurchaseVoucherTotalGrossAmt { get; set; }
        //////public decimal? PurchaseVoucherTotalItemDisAmount { get; set; }
        //////public decimal? PurchaseVoucherActualAmount { get; set; }
        //////public decimal? PurchaseVoucherDiscountPercentage { get; set; }
        //////public decimal? PurchaseVoucherTotalDiscountAmt { get; set; }
        //////public decimal? PurchaseVoucherVatAmount { get; set; }
        //////public decimal? PurchaseVoucherVatPercentage { get; set; }
        //////public string PurchaseVoucherVatRoundSign { get; set; }
        //////public decimal? PurchaseVoucherVatRountAmount { get; set; }
        //////public decimal? PurchaseVoucherDisAmount { get; set; }
        //////public decimal? PurchaseVoucherNetAmount { get; set; }
        //////public decimal? PurchaseVoucherTransportCost { get; set; }
        //////public decimal? PurchaseVoucherHandlingcharges { get; set; }
        //////public int PurchaseVoucherIssuedId { get; set; }
        //////public bool? PurchaseVoucherJobDirectPurchase { get; set; }
        //////public bool? PurchaseVoucherDelStatus { get; set; }
        //////public string CurrencyMasterCurrencyName { get; set; }
        //////public string SuppliersMasterSupplierName { get; set; }
        //////public string SuppliersMasterSupplierContactPerson { get; set; }
        //////public int? SuppliersMasterSupplierCountryId { get; set; }
        //////public int? SuppliersMasterSupplierCityId { get; set; }
        //////public string SuppliersMasterSupplierMobile { get; set; }
        //////public string SuppliersMasterSupplierRemarks { get; set; }
        //////public string SuppliersMasterSupplierVatNo { get; set; }
        //////public string CountryMasterCountryName { get; set; }
        //////public int? CityMasterCityId { get; set; }
        //////public string UnitMasterUnitShortName { get; set; }
        //////public long? ItemGroupId { get; set; }
        //////public string ItemGroupName { get; set; }
        //////public long? ItemBrandId { get; set; }
        //////public string ItemBrandName { get; set; }
        //////public string ItemMasterPartNo { get; set; }
        //////public string ItemMasterItemName { get; set; }
        //////public decimal? Expr1 { get; set; }
        //////public string PurchaseVoucherDetailsVoucherNo { get; set; }
        //////public int? PurchaseVoucherDetailsSno { get; set; }
        //////public int? PurchaseVoucherDetailsMaterialID { get; set; }
        //////public string PurchaseVoucherDetailsItemName { get; set; }
        //////public int? PurchaseVoucherDetailsUnitId { get; set; }
        //////public string PurchaseVoucherDetailsUnit { get; set; }
        //////public string PurchaseVoucherDetailsBatchCode { get; set; }
        //////public bool? PurchaseVoucherDetailsDelStatus { get; set; }
        //////public decimal? PurchaseVoucherDetailsSalesPrice1 { get; set; }
        //////public int? PurchaseVoucherDetailsQtndId { get; set; }
        //////public int? PurchaseVoucherDetailsQtnId { get; set; }
        //////public int? PurchaseVoucherDetailsPodId { get; set; }
        //////public int? PurchaseVoucherDetailsPoId { get; set; }
        //////public int? PurchaseVoucherDetailsPrdId { get; set; }
        //////public int? PurchaseVoucherDetailsPrId { get; set; }
        //////public int? PurchaseVoucherDetailsRfqdId { get; set; }
        //////public int? PurchaseVoucherDetailsRfqId { get; set; }
        //////public bool? PurchaseVoucherDetailsIsEdit { get; set; }
        //////public string PurchaseVoucherDetailsRemarks { get; set; }
        //////public decimal? PurchaseVoucherDetailsNetAmount { get; set; }
        //////public decimal? PurchaseVoucherDetailsVatAmount { get; set; }
        //////public decimal? PurchaseVoucherDetailsVatPercentage { get; set; }
        //////public decimal? PurchaseVoucherDetailsAmount { get; set; }
        //////public decimal? PurchaseVoucherDetailsDiscountAmoutPurchase { get; set; }
        //////public decimal? PurchaseVoucherDetailsGrossAmount { get; set; }
        //////public decimal? PurchaseVoucherDetailsRate { get; set; }
        //////public decimal? PurchaseVoucherDetailsQuantity { get; set; }
        //////public DateTime? PurchaseVoucherDetailsExpiryDate { get; set; }
        //////public DateTime? PurchaseVoucherDetailsManufactureDate { get; set; }
        //////public string SuppliersMasterSupplierTel1 { get; set; }
        //////public string SuppliersMasterSupplierFax { get; set; }
        //////public string LocationMasterLocationName { get; set; }
        //////public string JobMasterJobName { get; set; }
        public int PurchaseVoucherPurId { get; set; }
        public string PurchaseVoucherVoucherNo { get; set; }
        public int? PurchaseVoucherPurchaseIdNum { get; set; }
        public string PurchaseVoucherPurchaseRef { get; set; }
        public string PurchaseVoucherPurchaseType { get; set; }
        public string PurchaseVoucherGrNo { get; set; }
        public DateTime? PurchaseVoucherGrDate { get; set; }
        public int? PurchaseVoucherSpId { get; set; }
        public string PurchaseVoucherSpAccNo { get; set; }
        public decimal? PurchaseVoucherSpAmount { get; set; }
        public decimal? PurchaseVoucherFcSpAmount { get; set; }
        public DateTime? PurchaseVoucherPurchaseDate { get; set; }
        public string PurchaseVoucherLpoNo { get; set; }
        public DateTime? PurchaseVoucherLpoDate { get; set; }
        public string PurchaseVoucherQuatationNo { get; set; }
        public DateTime? PurchaseVoucherQuatationDate { get; set; }
        public decimal? PurchaseVoucherActualAmount { get; set; }
        public decimal? PurchaseVoucherNetAmount { get; set; }
        public decimal? PurchaseVoucherTransportCost { get; set; }
        public decimal? PurchaseVoucherHandlingCharges { get; set; }
        public decimal? PurchaseVoucherFcActualAmount { get; set; }
        public decimal? PurchaseVoucherFcNetAmount { get; set; }
        public string PurchaseVoucherDescription { get; set; }
        public double? PurchaseVoucherDrAccNo { get; set; }
        public decimal? PurchaseVoucherDrAmount { get; set; }
        public decimal? PurchaseVoucherFcDrAmount { get; set; }
        public string PurchaseVoucherDisYn { get; set; }
        public string PurchaseVoucherDisAcNo { get; set; }
        public decimal? PurchaseVoucherDisAmount { get; set; }
        public decimal? PurchaseVoucherFcDisAmount { get; set; }
        public string PurchaseVoucherStatus { get; set; }
        public int? PurchaseVoucherFsno { get; set; }
        public int? PurchaseVoucherUserId { get; set; }
        public decimal? PurchaseVoucherFcRate { get; set; }
        public int? PurchaseVoucherLocationId { get; set; }
        public string PurchaseVoucherSupplyInvoiceNo { get; set; }
        public decimal? PurchaseVoucherDiscountPercentage { get; set; }
        public int? PurchaseVoucherPoNo { get; set; }
        public int? PurchaseVoucherCurrencyId { get; set; }
        public int? PurchaseVoucherCompanyId { get; set; }
        public int? PurchaseVoucherJobId { get; set; }
        public string PurchaseVoucherBatchCode { get; set; }
        public string PurchaseVoucherCashSupplierName { get; set; }
        public string PurchaseVoucherDayBookNo { get; set; }
        public decimal? PurchaseVoucherVatAmount { get; set; }
        public decimal? PurchaseVoucherVatPercentage { get; set; }
        public string PurchaseVoucherVatRoundSign { get; set; }
        public decimal? PurchaseVoucherVatRoundAmount { get; set; }
        public string PurchaseVoucherVatNo { get; set; }
        public bool? PurchaseVoucherExcludeVat { get; set; }
        public int? PurchaseVoucherIssuedId { get; set; }
        public bool? PurchaseVoucherJobDirectPurchase { get; set; }
        public string PurchaseVoucherGrnoTmp { get; set; }
        public int? PurchaseVoucherPartyId { get; set; }
        public string PurchaseVoucherPartyName { get; set; }
        public string PurchaseVoucherPartyAddress { get; set; }
        public string PurchaseVoucherPartyVatNo { get; set; }
        public decimal? PurchaseVoucherTotalGrossAmt { get; set; }
        public decimal? PurchaseVoucherTotalItemDisAmount { get; set; }
        public decimal? PurchaseVoucherTotalDiscountAmt { get; set; }
        public bool? PurchaseVoucherDelStatus { get; set; }
        public string CurrencyMasterCurrencyName { get; set; }
        public string SuppliersMasterSupplierName { get; set; }
        public string SuppliersMasterSupplierContactPerson { get; set; }
        public int? SuppliersMasterSupplierCountryId { get; set; }
        public int? SuppliersMasterSupplierCityId { get; set; }
        public string SuppliersMasterSupplierMobile { get; set; }
        public string SuppliersMasterSupplierRemarks { get; set; }
        public string SuppliersMasterSupplierVatNo { get; set; }
        public string CountryMasterCountryName { get; set; }
        public int? CityMasterCityId { get; set; }
        public string UnitMasterUnitShortName { get; set; }
        public long? ItemGroupId { get; set; }
        public string ItemGroupName { get; set; }
        public long? ItemBrandId { get; set; }
        public string ItemBrandName { get; set; }
        public string ItemMasterPartNo { get; set; }
        public string ItemMasterItemName { get; set; }
        public int? Expr1 { get; set; }
        public string PurchaseVoucherDetailsVoucherNo { get; set; }
        public int? PurchaseVoucherDetailsSno { get; set; }
        public int? PurchaseVoucherDetailsMaterialId { get; set; }
        public string PurchaseVoucherDetailsItemName { get; set; }
        public int? PurchaseVoucherDetailsUnitId { get; set; }
        public string PurchaseVoucherDetailsUnit { get; set; }
        public string PurchaseVoucherDetailsBatchCode { get; set; }
        public bool? PurchaseVoucherDetailsDelStatus { get; set; }
        public decimal? PurchaseVoucherDetailsSalesPrice1 { get; set; }
        public int? PurchaseVoucherDetailsQtndId { get; set; }
        public int? PurchaseVoucherDetailsQtnId { get; set; }
        public int? PurchaseVoucherDetailsPodId { get; set; }
        public int? PurchaseVoucherDetailsPoId { get; set; }
        public int? PurchaseVoucherDetailsPrdId { get; set; }
        public int? PurchaseVoucherDetailsPrId { get; set; }
        public int? PurchaseVoucherDetailsRfqdId { get; set; }
        public int? PurchaseVoucherDetailsRfqId { get; set; }
        public bool? PurchaseVoucherDetailsIsEdit { get; set; }
        public string PurchaseVoucherDetailsRemarks { get; set; }
        public decimal? PurchaseVoucherDetailsNetAmount { get; set; }
        public decimal? PurchaseVoucherDetailsVatAmount { get; set; }
        public decimal? PurchaseVoucherDetailsVatPercentage { get; set; }
        public decimal? PurchaseVoucherDetailsAmount { get; set; }
        public decimal? PurchaseVoucherDetailsDiscountAmoutPurchase { get; set; }
        public decimal? PurchaseVoucherDetailsGrossAmount { get; set; }
        public decimal? PurchaseVoucherDetailsRate { get; set; }
        public decimal? PurchaseVoucherDetailsQuantity { get; set; }
        public DateTime? PurchaseVoucherDetailsExpiryDate { get; set; }
        public DateTime? PurchaseVoucherDetailsManufactureDate { get; set; }
        public string SuppliersMasterSupplierTel1 { get; set; }
        public string SuppliersMasterSupplierFax { get; set; }
        public string LocationMasterLocationName { get; set; }
        public string JobMasterJobName { get; set; }

    }
}
